import 'dart:io';

void main() {
  final Map<String, String> iconMap = {
    'Icons.apartment': 'CupertinoIcons.building_2_fill',
    'Icons.arrow_back_ios_new': 'CupertinoIcons.back',
    'Icons.arrow_forward_ios': 'CupertinoIcons.forward',
    'Icons.auto_awesome_rounded': 'CupertinoIcons.sparkles',
    'Icons.bag': 'CupertinoIcons.bag',
    'Icons.bag_fill': 'CupertinoIcons.bag_fill',
    'Icons.battery_full_rounded': 'CupertinoIcons.battery_100',
    'Icons.bolt': 'CupertinoIcons.bolt_fill',
    'Icons.chat_bubble_outline': 'CupertinoIcons.chat_bubble',
    'Icons.chat_bubble_text': 'CupertinoIcons.chat_bubble_text',
    'Icons.chat_bubble_text_fill': 'CupertinoIcons.chat_bubble_text_fill',
    'Icons.check': 'CupertinoIcons.checkmark_alt',
    'Icons.check_circle_outline': 'CupertinoIcons.checkmark_circle',
    'Icons.check_rounded': 'CupertinoIcons.checkmark_alt',
    'Icons.close': 'CupertinoIcons.clear',
    'Icons.close_rounded': 'CupertinoIcons.clear',
    'Icons.copy': 'CupertinoIcons.doc_on_doc',
    'Icons.crop_free_rounded': 'CupertinoIcons.crop',
    'Icons.crop_portrait_rounded': 'CupertinoIcons.crop',
    'Icons.dark_mode_outlined': 'CupertinoIcons.moon',
    'Icons.delete_outline_rounded': 'CupertinoIcons.trash',
    'Icons.edit_document': 'CupertinoIcons.doc_text',
    'Icons.edit_note_rounded': 'CupertinoIcons.pencil',
    'Icons.error_outline': 'CupertinoIcons.exclamationmark_triangle',
    'Icons.flight_rounded': 'CupertinoIcons.airplane',
    'Icons.heart': 'CupertinoIcons.heart',
    'Icons.heart_fill': 'CupertinoIcons.heart_fill',
    'Icons.home': 'CupertinoIcons.house_fill',
    'Icons.home_outlined': 'CupertinoIcons.house',
    'Icons.home_rounded': 'CupertinoIcons.house_fill',
    'Icons.house': 'CupertinoIcons.house',
    'Icons.house_fill': 'CupertinoIcons.house_fill',
    'Icons.keyboard_arrow_down': 'CupertinoIcons.chevron_down',
    'Icons.keyboard_arrow_down_rounded': 'CupertinoIcons.chevron_down',
    'Icons.light_mode_outlined': 'CupertinoIcons.sun_max',
    'Icons.location_on': 'CupertinoIcons.location_solid',
    'Icons.location_on_rounded': 'CupertinoIcons.location_solid',
    'Icons.logout_rounded': 'CupertinoIcons.square_arrow_right',
    'Icons.mic': 'CupertinoIcons.mic_fill',
    'Icons.more_vert_rounded': 'CupertinoIcons.ellipsis_vertical',
    'Icons.navigation_rounded': 'CupertinoIcons.location_north_fill',
    'Icons.open_in_new_rounded': 'CupertinoIcons.arrow_up_right_square',
    'Icons.phone_android': 'CupertinoIcons.device_phone_portrait',
    'Icons.phone_iphone': 'CupertinoIcons.device_phone_portrait',
    'Icons.radio_button_unchecked': 'CupertinoIcons.circle',
    'Icons.refresh_rounded': 'CupertinoIcons.refresh_thick',
    'Icons.rotate_right_rounded': 'CupertinoIcons.rotate_right',
    'Icons.save_rounded': 'CupertinoIcons.floppy_disk',
    'Icons.screen_rotation_outlined': 'CupertinoIcons.rotate_right',
    'Icons.search': 'CupertinoIcons.search',
    'Icons.share_rounded': 'CupertinoIcons.share',
    'Icons.signal_cellular_4_bar': 'CupertinoIcons.antenna_radiowaves_left_right',
    'Icons.speed_rounded': 'CupertinoIcons.speedometer',
    'Icons.star_rounded': 'CupertinoIcons.star_fill',
    'Icons.tablet_mac': 'CupertinoIcons.device_tablet',
    'Icons.tag': 'CupertinoIcons.tag',
    'Icons.tag_fill': 'CupertinoIcons.tag_fill',
    'Icons.tips_and_updates': 'CupertinoIcons.lightbulb_fill',
    'Icons.train_outlined': 'CupertinoIcons.tram_fill',
    'Icons.train_rounded': 'CupertinoIcons.tram_fill',
    'Icons.tram_outlined': 'CupertinoIcons.tram_fill',
    'Icons.undo_rounded': 'CupertinoIcons.arrow_uturn_left',
    'Icons.warning_amber_rounded': 'CupertinoIcons.exclamationmark_triangle_fill',
    'Icons.whatsapp': 'CupertinoIcons.chat_bubble_2_fill',
    'Icons.wifi': 'CupertinoIcons.wifi',
    'Icons.wifi_tethering': 'CupertinoIcons.personalhotspot',

    'Iconsax.add': 'CupertinoIcons.add',
    'Iconsax.add_circle': 'CupertinoIcons.add_circled',
    'Iconsax.airplane': 'CupertinoIcons.airplane',
    'Iconsax.arrange_circle': 'CupertinoIcons.arrow_2_circlepath_circle',
    'Iconsax.arrow_down_1': 'CupertinoIcons.chevron_down',
    'Iconsax.arrow_left_2': 'CupertinoIcons.chevron_left',
    'Iconsax.arrow_right_1': 'CupertinoIcons.chevron_right',
    'Iconsax.arrow_right_3': 'CupertinoIcons.chevron_right',
    'Iconsax.arrow_up_3': 'CupertinoIcons.chevron_up',
    'Iconsax.box': 'CupertinoIcons.cube_box_fill',
    'Iconsax.broom': 'CupertinoIcons.paintbrush',
    'Iconsax.brush_1': 'CupertinoIcons.paintbrush_fill',
    'Iconsax.bucket': 'CupertinoIcons.drop_fill',
    'Iconsax.building': 'CupertinoIcons.building_2_fill',
    'Iconsax.building_3': 'CupertinoIcons.building_2_fill',
    'Iconsax.building_4': 'CupertinoIcons.building_2_fill',
    'Iconsax.buildings': 'CupertinoIcons.building_2_fill',
    'Iconsax.buildings_2': 'CupertinoIcons.building_2_fill',
    'Iconsax.bus': 'CupertinoIcons.bus',
    'Iconsax.calendar': 'CupertinoIcons.calendar',
    'Iconsax.calendar5': 'CupertinoIcons.calendar',
    'Iconsax.calendar_1': 'CupertinoIcons.calendar',
    'Iconsax.calendar_15': 'CupertinoIcons.calendar',
    'Iconsax.call': 'CupertinoIcons.phone_fill',
    'Iconsax.call_calling': 'CupertinoIcons.phone_fill',
    'Iconsax.camera': 'CupertinoIcons.camera_fill',
    'Iconsax.car': 'CupertinoIcons.car_detailed',
    'Iconsax.card_pos': 'CupertinoIcons.creditcard_fill',
    'Iconsax.category': 'CupertinoIcons.square_grid_2x2_fill',
    'Iconsax.chart_21': 'CupertinoIcons.chart_bar_alt_fill',
    'Iconsax.clock': 'CupertinoIcons.clock_fill',
    'Iconsax.close_circle': 'CupertinoIcons.clear_circled_solid',
    'Iconsax.close_circle5': 'CupertinoIcons.clear_circled_solid',
    'Iconsax.coffee': 'CupertinoIcons.circle_grid_hex',
    'Iconsax.computing': 'CupertinoIcons.desktopcomputer',
    'Iconsax.cpu': 'CupertinoIcons.device_laptop',
    'Iconsax.crop': 'CupertinoIcons.crop',
    'Iconsax.cup': 'CupertinoIcons.circle_grid_hex',
    'Iconsax.danger': 'CupertinoIcons.exclamationmark_triangle_fill',
    'Iconsax.data': 'CupertinoIcons.chart_bar_fill',
    'Iconsax.document_download': 'CupertinoIcons.doc_arrow_down',
    'Iconsax.document_text': 'CupertinoIcons.doc_text_fill',
    'Iconsax.drop': 'CupertinoIcons.drop_fill',
    'Iconsax.edit_2': 'CupertinoIcons.pencil',
    'Iconsax.element_4': 'CupertinoIcons.square_grid_2x2',
    'Iconsax.eye': 'CupertinoIcons.eye_solid',
    'Iconsax.eye_slash': 'CupertinoIcons.eye_slash_fill',
    'Iconsax.filter_tick': 'CupertinoIcons.slider_horizontal_3',
    'Iconsax.flag': 'CupertinoIcons.flag_fill',
    'Iconsax.flash': 'CupertinoIcons.bolt_fill',
    'Iconsax.flash_1': 'CupertinoIcons.bolt_fill',
    'Iconsax.folder_2': 'CupertinoIcons.folder_fill',
    'Iconsax.gallery': 'CupertinoIcons.photo',
    'Iconsax.gallery_add': 'CupertinoIcons.photo_on_rectangle',
    'Iconsax.gallery_slash': 'CupertinoIcons.photo',
    'Iconsax.gps': 'CupertinoIcons.location_fill',
    'Iconsax.heart': 'CupertinoIcons.heart',
    'Iconsax.home': 'CupertinoIcons.house_fill',
    'Iconsax.home_2': 'CupertinoIcons.house_fill',
    'Iconsax.home_hashtag': 'CupertinoIcons.house_fill',
    'Iconsax.house': 'CupertinoIcons.house_fill',
    'Iconsax.image': 'CupertinoIcons.photo',
    'Iconsax.info_circle': 'CupertinoIcons.info_circle_fill',
    'Iconsax.key': 'CupertinoIcons.lock_fill',
    'Iconsax.lamp_1': 'CupertinoIcons.lightbulb_fill',
    'Iconsax.lamp_on': 'CupertinoIcons.lightbulb_fill',
    'Iconsax.layer': 'CupertinoIcons.square_stack_3d_up_fill',
    'Iconsax.link_21': 'CupertinoIcons.link',
    'Iconsax.location': 'CupertinoIcons.location_solid',
    'Iconsax.location5': 'CupertinoIcons.location_solid',
    'Iconsax.location_tick': 'CupertinoIcons.location_solid',
    'Iconsax.lock': 'CupertinoIcons.lock_fill',
    'Iconsax.logout': 'CupertinoIcons.square_arrow_right',
    'Iconsax.magic_star': 'CupertinoIcons.wand_stars',
    'Iconsax.magicpen': 'CupertinoIcons.wand_stars',
    'Iconsax.map_1': 'CupertinoIcons.map_fill',
    'Iconsax.maximize4': 'CupertinoIcons.fullscreen',
    'Iconsax.maximize_4': 'CupertinoIcons.fullscreen',
    'Iconsax.medal_star': 'CupertinoIcons.rosette',
    'Iconsax.message': 'CupertinoIcons.chat_bubble_text',
    'Iconsax.mobile': 'CupertinoIcons.device_phone_portrait',
    'Iconsax.moon': 'CupertinoIcons.moon_fill',
    'Iconsax.moon5': 'CupertinoIcons.moon_fill',
    'Iconsax.notification': 'CupertinoIcons.bell_fill',
    'Iconsax.notification5': 'CupertinoIcons.bell_fill',
    'Iconsax.notification_bing': 'CupertinoIcons.bell_fill',
    'Iconsax.people': 'CupertinoIcons.person_3_fill',
    'Iconsax.profile_2user': 'CupertinoIcons.person_2_fill',
    'Iconsax.radar_2': 'CupertinoIcons.dot_radiowaves_right',
    'Iconsax.ranking': 'CupertinoIcons.chart_bar_alt_fill',
    'Iconsax.receipt_item': 'CupertinoIcons.doc_text_fill',
    'Iconsax.refresh': 'CupertinoIcons.refresh_thick',
    'Iconsax.routing': 'CupertinoIcons.arrow_swap',
    'Iconsax.routing_2': 'CupertinoIcons.arrow_swap',
    'Iconsax.search_normal': 'CupertinoIcons.search',
    'Iconsax.search_normal_1': 'CupertinoIcons.search',
    'Iconsax.search_status': 'CupertinoIcons.search',
    'Iconsax.security_user': 'CupertinoIcons.shield_fill',
    'Iconsax.send_1': 'CupertinoIcons.paperplane_fill',
    'Iconsax.send_2': 'CupertinoIcons.paperplane_fill',
    'Iconsax.setting_2': 'CupertinoIcons.settings',
    'Iconsax.setting_4': 'CupertinoIcons.settings',
    'Iconsax.shield': 'CupertinoIcons.shield_fill',
    'Iconsax.shield_tick': 'CupertinoIcons.shield_fill',
    'Iconsax.shop': 'CupertinoIcons.tag_fill',
    'Iconsax.sidebar_left': 'CupertinoIcons.sidebar_left',
    'Iconsax.sidebar_right': 'CupertinoIcons.sidebar_right',
    'Iconsax.slash': 'CupertinoIcons.nosign',
    'Iconsax.sms': 'CupertinoIcons.mail_solid',
    'Iconsax.sort': 'CupertinoIcons.sort_down',
    'Iconsax.star': 'CupertinoIcons.star_fill',
    'Iconsax.star1': 'CupertinoIcons.star_fill',
    'Iconsax.sun_1': 'CupertinoIcons.sun_max_fill',
    'Iconsax.sun_fog': 'CupertinoIcons.sun_dust_fill',
    'Iconsax.tag': 'CupertinoIcons.tag_fill',
    'Iconsax.tick_circle': 'CupertinoIcons.checkmark_alt',
    'Iconsax.tick_circle5': 'CupertinoIcons.checkmark_alt',
    'Iconsax.timer_1': 'CupertinoIcons.timer',
    'Iconsax.timer_pause': 'CupertinoIcons.timer',
    'Iconsax.trash': 'CupertinoIcons.trash',
    'Iconsax.user': 'CupertinoIcons.person_fill',
    'Iconsax.user_tag': 'CupertinoIcons.person_fill',
    'Iconsax.user_tick': 'CupertinoIcons.person_fill',
    'Iconsax.verify': 'CupertinoIcons.check_mark_circled_solid',
    'Iconsax.verify5': 'CupertinoIcons.check_mark_circled_solid',
    'Iconsax.wallet_2': 'CupertinoIcons.creditcard_fill',
    'Iconsax.wallet_3': 'CupertinoIcons.creditcard_fill',
    'Iconsax.warning_2': 'CupertinoIcons.exclamationmark_triangle_fill',
    'Iconsax.wind_2': 'CupertinoIcons.wind'
  };

  final dir = Directory('lib');
  final regex = RegExp(r'(Iconsax|Icons)\.([a-zA-Z0-9_]+)');

  for (final file in dir.listSync(recursive: true)) {
    if (file is File && file.path.endsWith('.dart')) {
      String content = file.readAsStringSync();
      bool modified = false;

      final replacedContent = content.replaceAllMapped(regex, (match) {
        final original = match.group(0)!;
        if (iconMap.containsKey(original)) {
          modified = true;
          return iconMap[original]!;
        }
        return original;
      });

      if (modified) {
        String finalContent = replacedContent;
        if (!finalContent.contains("package:flutter/cupertino.dart")) {
           finalContent = "import 'package:flutter/cupertino.dart';\n" + finalContent;
        }
        file.writeAsStringSync(finalContent);
        print("Updated dart file");
      }
    }
  }
}
